apiVersion: v1
kind: Secret
metadata:
  name: freezer-webhook-certs
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
    networking.knative.dev/ingress-provider: istio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freezer-webhook
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
spec:
  selector:
    matchLabels:
      app: freezer-webhook
      role: freezer-webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: freezer-webhook
        role: freezer-webhook
        serving.knative.dev/release: devel
    spec:
      serviceAccountName: controller
      containers:
      - name: webhook
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: ko://github.com/julz/freeze-proxy/cmd/webhook
        env:
        - name: FREEZE_PROXY_IMAGE
          value: ko://github.com/julz/freeze-proxy/cmd/freezeproxy
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: extensions.knative.dev/freeze-proxy
        - name: WEBHOOK_NAME
          value: freezer-webhook
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        - name: https-webhook
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: freezer-webhook
  namespace: knative-serving
  labels:
    role: freezer-webhook
    serving.knative.dev/release: devel
spec:
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: freezer-webhook
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.freeze.extensions.knative.dev
  labels:
    serving.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: freezer-webhook
      namespace: knative-serving
  failurePolicy: Fail
  sideEffects: None
  objectSelector:
    matchExpressions:
      - {key: "serving.knative.dev/configuration", operator: Exists}
  name: webhook.freeze.extensions.knative.dev
