apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: freeze-tokenreview-binding
  namespace: knative-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: freeze-tokenreview
  namespace: knative-serving
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: freeze-daemon
  namespace: knative-serving
spec:
  selector:
    matchLabels:
      name: freeze-daemon
  template:
    metadata:
      labels:
        name: freeze-daemon
    spec:
      serviceAccountName: freeze-tokenreview # TODO: swap for account with just tokenreview
      containers:
        - name: daemon
          securityContext:
            runAsUser: 0
          image: ko://github.com/julz/freeze-proxy/cmd/daemon
          ports:
            - containerPort: 8080
              hostPort: 9696
          volumeMounts:
            - name: containerd-socket
              mountPath: /var/run/containerd/containerd.sock
      volumes:
        - name: containerd-socket
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
